### ISSUE TITLE
composer

### ISSUE THREAD

**Issue by trancesmile** [vova07/yii2-users-module#6]
Please fix composer.json. Rename yii2-rbac-module in yii2-start-rbac-module
- Installing vova07/yii2-start-rbac-module (0.1.0)
  Downloading: 100%
- Installing vova07/yii2-rbac-module (0.2.0)
  Downloading: 100%
  Invalid zip file, retrying...
- Installing vova07/yii2-rbac-module (0.2.0)
  Downloading: 100%
  Invalid zip file, retrying...
- Installing vova07/yii2-rbac-module (0.2.0)
  Downloading: 100%
  Failed to download vova07/yii2-rbac-module from dist: 'D:\OpenServer\domains\bilyky.loc\vendor/vova07/yii2-rbac-module/697b991be02adcf7fa331869abcf4f8c' is not a zip archive.
  Now trying to download from source
- Installing vova07/yii2-rbac-module (0.2.0)
  Cloning 30d6de084d1f13b64a7212f9a2b9fe5f53aabff9
  30d6de084d1f13b64a7212f9a2b9fe5f53aabff9 is gone (history was rewritten?)

**Comment by vntuanbk** [comment]
Please fix:
Error when i try with desktop composer.
[code]
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing vova07/yii2-rbac-module (0.1.0)
    Downloading: 100%
    Invalid zip file, retrying...
  - Installing vova07/yii2-rbac-module (0.1.0)
    Downloading: 100%
    Invalid zip file, retrying...
  - Installing vova07/yii2-rbac-module (0.1.0)
    Downloading: 100%
    Failed to download vova07/yii2-rbac-module from dist: '[PATH]\
vendor/vova07/yii2-rbac-module/d0f123432f26a78a04f46bde0613e349' is not a zip ar
chive.
    Now trying to download from source
  - Installing vova07/yii2-rbac-module (0.1.0)
    Cloning 11dc36ee0ad97f3265c52d938d57f5d57e9ffa1f



  [RuntimeException]
  Failed to clone git@github.com:vova07/yii2-start-rbac-module.git, git was n
  ot found, check that it is installed and in your PATH env.
  'git' is not recognized as an internal or external command,
  operable program or batch file.
[/code]
